-- Development seed.
--
-- Intentionally EMPTY of products.
--
-- Stores, categories and regions are created by the migrations — they are
-- structure, not data. Products used to be seeded with invented prices so the
-- UI could be exercised before an adapter existed. That adapter exists now, so
-- fake figures that look real are a liability rather than a help.
--
-- To fill the catalogue:
--
--   pnpm run db:reset                       (structure only)
--   pnpm run ingest -- --max 500            (real products from Éxito)
--
-- Without ingestion the app shows its empty state, which already says the
-- catalogue is filled by the price pipeline. That is honest.
